version: "3.2"

services:
  couchdb1:
    image: couchdb:3.3.1
    command: -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET:-123456}"
      - "NODENAME=172.16.238.11"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.11
    ports:
      - "15984:5984"

  couchdb2:
    image: couchdb:3.3.1
    command: -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET:-123456}"
      - "NODENAME=172.16.238.12"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.12
    ports:
      - "25984:5984"

  couchdb3:
    image: couchdb:3.3.1
    command: -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET:-123456}"
      - "NODENAME=172.16.238.13"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.13
    ports:
      - "35984:5984"

  cluster-setup:
    build: .
#    image: gesellix/couchdb-cluster-config:latest
    command: >-
      setup
      --delay 10s
      --timeout 60s
      --username ${COUCHDB_USER:-admin}
      --password ${COUCHDB_PASSWORD:-password}
      -nodes 172.16.238.11
      -nodes 172.16.238.12
      -nodes 172.16.238.13
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.99

networks:
  couchdb-cluster:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
