---
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -v ./...
...
