---
name: build
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -v ./...
...
